// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scadex.RemoteDesk.DataAccess;

#nullable disable

namespace Scadex.RemoteDesk.Data.Migrations
{
    [DbContext(typeof(RemoteDeskDbContext))]
    [Migration("20260929150515_InitialRemoteDesk")]
    partial class InitialRemoteDesk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("remotedesk")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Scadex.RemoteDesk.Model.Entities.ScreenSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MediaPath")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("MonitorIndex")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StopReason")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StoppedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("DeviceId", "MonitorIndex")
                        .IsUnique()
                        .HasFilter("[Status] IN (1, 2, 3, 4)");

                    b.ToTable("ScreenSession", "remotedesk");
                });

            modelBuilder.Entity("Scadex.RemoteDesk.Model.Entities.ScreenViewLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MonitorIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("ScreenSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScreenSessionId");

                    b.HasIndex("DeviceId", "StartedUtc");

                    b.HasIndex("UserId", "StartedUtc");

                    b.ToTable("ScreenViewLog", "remotedesk");
                });

            modelBuilder.Entity("Scadex.RemoteDesk.Model.Entities.ScreenViewLog", b =>
                {
                    b.HasOne("Scadex.RemoteDesk.Model.Entities.ScreenSession", "ScreenSession")
                        .WithMany()
                        .HasForeignKey("ScreenSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ScreenSession");
                });
#pragma warning restore 612, 618
        }
    }
}
