// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scadex.Signalization.Data;

#nullable disable

namespace Scadex.Signalization.Data.Migrations
{
    [DbContext(typeof(SignalizationDbContext))]
    partial class SignalizationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("signalization")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Scadex.Signalization.Entities.OperatorSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AwaitingCardDueAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CabinetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DurationSec")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Flags")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MaxDurationDueAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OuterDoorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OuterDoorNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("SirenOffDueAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SirenReleasedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SirenRequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OuterDoorId")
                        .IsUnique()
                        .HasFilter("[EndedAtUtc] IS NULL");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("CabinetId", "StartedAtUtc");

                    b.ToTable("OperatorSession", "signalization");
                });

            modelBuilder.Entity("Scadex.Signalization.Entities.OperatorSessionCapture", b =>
                {
                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<long>("CameraCaptureId")
                        .HasColumnType("bigint");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("SessionId", "CameraCaptureId");

                    b.ToTable("OperatorSessionCapture", "signalization");
                });

            modelBuilder.Entity("Scadex.Signalization.Entities.OperatorSessionEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CameraCaptureId")
                        .HasColumnType("bigint");

                    b.Property<string>("CardIdRaw")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Detail")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("DeviceCommandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InnerDoorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "OccurredAtUtc");

                    b.ToTable("OperatorSessionEvent", "signalization");
                });

            modelBuilder.Entity("Scadex.Signalization.Entities.OperatorSessionOperator", b =>
                {
                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorityNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CardIdRaw")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("FirstCardAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("LastCardAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("SessionId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("OperatorSessionOperator", "signalization");
                });

            modelBuilder.Entity("Scadex.Signalization.Entities.SignalAuthority", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("RoleId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("Authority", "signalization");
                });

            modelBuilder.Entity("Scadex.Signalization.Entities.SignalCabinet", b =>
                {
                    b.Property<Guid>("CabinetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AwaitingCardTimeoutSec")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntrySnapshotCount")
                        .HasColumnType("int");

                    b.Property<int>("EntrySnapshotIntervalMs")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("SessionMaxDurationMin")
                        .HasColumnType("int");

                    b.Property<int>("SirenDurationSec")
                        .HasColumnType("int");

                    b.Property<Guid?>("SirenIoChannelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CabinetId");

                    b.ToTable("Cabinet", "signalization");
                });

            modelBuilder.Entity("Scadex.Signalization.Entities.SignalCabinetState", b =>
                {
                    b.Property<Guid>("CabinetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastSirenCommandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SirenChangedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SirenIsOn")
                        .HasColumnType("bit");

                    b.HasKey("CabinetId");

                    b.ToTable("CabinetState", "signalization");
                });

            modelBuilder.Entity("Scadex.Signalization.Entities.SignalInnerDoor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("LockIoChannelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("OuterDoorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SwitchIoChannelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SwitchOpenValue")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("UnlockTurnsOn")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorityId");

                    b.HasIndex("OuterDoorId");

                    b.HasIndex("SwitchIoChannelId");

                    b.ToTable("InnerDoor", "signalization");
                });

            modelBuilder.Entity("Scadex.Signalization.Entities.SignalInnerDoorState", b =>
                {
                    b.Property<Guid>("InnerDoorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastCommandId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InnerDoorId");

                    b.ToTable("InnerDoorState", "signalization");
                });

            modelBuilder.Entity("Scadex.Signalization.Entities.SignalOuterDoor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CabinetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CameraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("SwitchIoChannelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SwitchOpenValue")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime?>("UpdateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.HasIndex("SwitchIoChannelId");

                    b.ToTable("OuterDoor", "signalization");
                });

            modelBuilder.Entity("Scadex.Signalization.Entities.OperatorSessionCapture", b =>
                {
                    b.HasOne("Scadex.Signalization.Entities.OperatorSession", "Session")
                        .WithMany("Captures")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Scadex.Signalization.Entities.OperatorSessionEvent", b =>
                {
                    b.HasOne("Scadex.Signalization.Entities.OperatorSession", "Session")
                        .WithMany("Events")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Scadex.Signalization.Entities.OperatorSessionOperator", b =>
                {
                    b.HasOne("Scadex.Signalization.Entities.OperatorSession", "Session")
                        .WithMany("Operators")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Scadex.Signalization.Entities.SignalInnerDoor", b =>
                {
                    b.HasOne("Scadex.Signalization.Entities.SignalAuthority", "Authority")
                        .WithMany()
                        .HasForeignKey("AuthorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Scadex.Signalization.Entities.SignalOuterDoor", "OuterDoor")
                        .WithMany("InnerDoors")
                        .HasForeignKey("OuterDoorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Authority");

                    b.Navigation("OuterDoor");
                });

            modelBuilder.Entity("Scadex.Signalization.Entities.SignalInnerDoorState", b =>
                {
                    b.HasOne("Scadex.Signalization.Entities.SignalInnerDoor", null)
                        .WithOne("State")
                        .HasForeignKey("Scadex.Signalization.Entities.SignalInnerDoorState", "InnerDoorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scadex.Signalization.Entities.SignalOuterDoor", b =>
                {
                    b.HasOne("Scadex.Signalization.Entities.SignalCabinet", "Cabinet")
                        .WithMany("OuterDoors")
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cabinet");
                });

            modelBuilder.Entity("Scadex.Signalization.Entities.OperatorSession", b =>
                {
                    b.Navigation("Captures");

                    b.Navigation("Events");

                    b.Navigation("Operators");
                });

            modelBuilder.Entity("Scadex.Signalization.Entities.SignalCabinet", b =>
                {
                    b.Navigation("OuterDoors");
                });

            modelBuilder.Entity("Scadex.Signalization.Entities.SignalInnerDoor", b =>
                {
                    b.Navigation("State");
                });

            modelBuilder.Entity("Scadex.Signalization.Entities.SignalOuterDoor", b =>
                {
                    b.Navigation("InnerDoors");
                });
#pragma warning restore 612, 618
        }
    }
}
